"""Add organization to the user table

Revision ID: bb90ec18cc9b
Revises: 1865c877a8a8
Create Date: 2024-09-18 15:18:56.236319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb90ec18cc9b'
down_revision = '1865c877a8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=255), nullable=False, server_default='default_organization'))
        batch_op.create_unique_constraint(None, ['organization'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
